---
title: "Springboard Foundations of Data Science Code"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Predicting the Accuracy of Credit Card Default - R Code

## Data Wrangling

``` {r, eval = FALSE}
# Load all packages used in analysis and read in data set
library(readr)
library(plyr)
library(tidyr)
library(dplyr)
library(varhandle)
library(ggplot2)
library(caTools)
library(rpart)
library(rpart.plot)
library(randomForest)
dcc <- read_csv("~/dcc.csv")
```

``` {r eval = FALSE}
# Look at structure of dcc
str(dcc)
```

``` {r eval = FALSE}
# Change column names from X1, X2 etc to the value in row 2
colnames(dcc) <- dcc[1,]

# Delete row 2 to remove duplicate titles
dcc = dcc[-1,]

# Remove ID column (column #1)
dcc <- dcc[-1]

# Clean up column names
names(dcc) <- c("LimitAmt", "Gender", "Education", "Marriage", "Age", "StatusSep05", "StatusAug05"
                , "StatusJul05", "StatusJun05", "StatusMay05", "StatusApr05", "BalSep05", "BalAug05",
                "BalJul05", "BalJun05", "BalMay05", "BalApr05", "PayAmtSep05", "PayAmtAug05",
                "PayAmtJul05", "PayAmtJun05", "PayAmtMay05", "PayAmtApr05", "DefaultOct05")
```

``` {r eval = FALSE}
# Transform data set to data frame
dcc <- as.data.frame(dcc)
```

``` {r eval = FALSE}
# Convert each column from character to numeric
dcc[] <- lapply(dcc, function(x) as.numeric(x))
```

``` {r eval = FALSE}
# Convert values 4,5, and 6 in Education column to 0 as they all represent "Other"
dcc$Education[dcc$Education == 4] <- 0
dcc$Education[dcc$Education == 5] <- 0
dcc$Education[dcc$Education == 6] <- 0
```

``` {r eval = FALSE}
# Add duplicate columns with different character types
dcc$Gender1 <- paste(dcc$Gender)
dcc$Education1 <- paste(dcc$Education)
dcc$Marriage1 <- paste(dcc$Marriage)
dcc$Status1Sep05 <- paste(dcc$StatusSep05)
dcc$Status1Aug05 <- paste(dcc$StatusAug05)
dcc$Status1Jul05 <- paste(dcc$StatusJul05)
dcc$Status1Jun05 <- paste(dcc$StatusJun05)
dcc$Status1May05 <- paste(dcc$StatusMay05)
dcc$Status1Apr05 <- paste(dcc$StatusApr05)
dcc$Default1Oct05 <- paste(dcc$DefaultOct05)
```

``` {r eval = FALSE}
# Change values from integer to categorical for Sex, Education, Marriage, Default columns

dcc$Gender1 <- factor(dcc$Gender1)    
levels(dcc$Gender1) <- c("Male", "Female")

dcc$Education1 <- factor(dcc$Education1)
levels(dcc$Education1) <- c("Other", "GradSch", "Bachelors", "HS")

dcc$Marriage1 <- factor(dcc$Marriage1)
levels(dcc$Marriage1) <- c("Div", "Mar", "Single", "Div")

dcc$Default1Oct05 <- factor(dcc$Default1Oct05)  #NDef and Def stand for No Default and Default
levels(dcc$Default1Oct05) <- c("No Default", "Default")

# Change values from integer to categorical for payment status columns from Apr05 to May05

dcc$Status1Sep05 <- factor(dcc$Status1Sep05)
dcc$Status1Aug05 <- factor(dcc$Status1Aug05)
dcc$Status1Jul05 <- factor(dcc$Status1Jul05)
dcc$Status1Jun05 <- factor(dcc$Status1Jun05)
dcc$Status1May05 <- factor(dcc$Status1May05)
dcc$Status1Apr05 <- factor(dcc$Status1Apr05)

# Change values from -2, -1, etc to character strings

levels(dcc$Status1Sep05)<- c("SepPaid", "SepNoCons", "SepRev", "Sep1MoD", "Sep2MoD", "Sep3MoD", "Sep4MoD", "Sep5MoD", "Sep6MoD", "Sep7MoD", "Sep8MoD")
levels(dcc$Status1Aug05)<- c("AugPaid", "AugNoCons", "AugRev", "Aug1MoD", "Aug2MoD", "Aug3MoD", "Aug4MoD", "Aug5MoD", "Aug6MoD", "Aug7MoD", "Aug8MoD")
levels(dcc$Status1Jul05)<- c("JulPaid", "JulNoCons", "JulRev", "Jul1MoD", "Jul2MoD", "Jul3MoD", "Jul4MoD", "Jul5MoD", "Jul6MoD", "Jul7MoD", "Jul8MoD")
levels(dcc$Status1Jun05)<- c("JunPaid", "JunNoCons", "JunRev", "Jun1MoD", "Jun2MoD", "Jun3MoD", "Jun4MoD", "Jun5MoD", "Jun6MoD", "Jun7MoD", "Jun8MoD")
levels(dcc$Status1May05)<- c("MayPaid", "MayNoCons", "MayRev", "May2MoD", "May3MoD", "May4MoD", "May5MoD", "May6MoD", "May7MoD", "May8MoD")
levels(dcc$Status1Apr05)<- c("AprPaid", "AprNoCons", "AprRev", "Apr2MoD", "Apr3MoD", "Apr4MoD", "Apr5MoD", "Apr6MoD", "Apr7MoD", "Apr8MoD")
```

``` {r eval = FALSE}
# Create bins for credit limit and age so we can group borrowers into different categories
# The LAmtCut and AgeCut variables represent where the cutoff for each bin is

dcc$LimitAmtBin <- paste(dcc$LimitAmt)
dcc$LimitAmtBin <- as.numeric(as.character(dcc$LimitAmtBin))
sapply(dcc$LimitAmtBin, class)
LAmtCut <- cut(dcc$LimitAmtBin, breaks = c(0, 10000, 25000, 50000, 100000, 250000, 500000, 1000000),
               labels = c("10KLimit", "25KLimit", "50KLimit", "100KLimit", "250KLimit", "500KLimit", "1MilLimit"))
dcc$LimitAmtBin <- LAmtCut

dcc$AgeBin <- paste(dcc$Age)
dcc$AgeBin <- as.numeric(as.character(dcc$AgeBin))
sapply(dcc$AgeBin, class)
AgeCut <- cut(dcc$AgeBin, breaks = c(20, 25, 30, 35, 40, 50, 60, 80),
              labels = c("25Y", "30Y", "35Y", "40Y", "50Y", "60Y", "80Y"))
dcc$AgeBin <- AgeCut
```

``` {r eval = FALSE}
# Creat bins for monthly balance and monthly pay amount variables in order to group into categories
dcc$BalBinSep05 <- paste(dcc$BalSep05)
dcc$BalBinSep05 <- as.numeric(as.character(dcc$BalBinSep05))
sapply(dcc$BalBinSep05, class)
BalSepCut <- cut(dcc$BalBinSep05, breaks = c(-1000000, -1, 0, 3000, 10000, 25000, 50000, 100000, 250000, 500000, 1000000),
                 labels = c("NegSepBal", "ZeroSepBal", "3KSepBal", "10KSepBal", "25KSepBal", "50KSepBal", "100KSepBal", "250KSepBal", "500KSepBal", "1milSepBal"))
dcc$BalBinSep05 <- BalSepCut

dcc$BalBinAug05 <- paste(dcc$BalAug05)
dcc$BalBinAug05 <- as.numeric(as.character(dcc$BalBinAug05))
sapply(dcc$BalBinAug05, class)
BalAugCut <- cut(dcc$BalBinAug05, breaks = c(-1000000, -1, 0, 3000, 10000, 25000, 50000, 100000, 250000, 500000, 1000000),
                 labels = c("NegAugBal", "ZeroAugBal", "3KAugBal", "10KAugBal", "25KAugBal", "50KAugBal", "100KAugBal", "250KAugBal", "500KAugBal", "1milAugBal"))
dcc$BalBinAug05 <- BalAugCut

dcc$BalBinJul05 <- paste(dcc$BalJul05)
dcc$BalBinJul05 <- as.numeric(as.character(dcc$BalBinJul05))
sapply(dcc$BalBinJul05, class)
BalJulCut <- cut(dcc$BalBinJul05, breaks = c(-1000000, -1, 0, 3000, 10000, 25000, 50000, 100000, 250000, 500000, 1000000),
                 labels = c("NegJulBal", "ZeroJulBal", "3KJulBal", "10KJulBal", "25KJulBal", "50KJulBal", "100KJulBal", "250KJulBal", "500KJulBal", "1milJulBal"))
dcc$BalBinJul05 <- BalJulCut

dcc$BalBinJun05 <- paste(dcc$BalJun05)
dcc$BalBinJun05 <- as.numeric(as.character(dcc$BalBinJun05))
sapply(dcc$BalBinJun05, class)
BalJunCut <- cut(dcc$BalBinJun05, breaks = c(-1000000, -1, 0, 3000, 10000, 25000, 50000, 100000, 250000, 500000, 1000000),
                 labels = c("NegJunBal", "ZeroJunBal", "3KJunBal", "10KJunBal", "25KJunBal", "50KJunBal", "100KJunBal", "250KJunBal", "500KJunBal", "1milJunBal"))
dcc$BalBinJun05 <- BalJunCut

dcc$BalBinMay05 <- paste(dcc$BalMay05)
dcc$BalBinMay05 <- as.numeric(as.character(dcc$BalBinMay05))
sapply(dcc$BalBinMay05, class)
BalMayCut <- cut(dcc$BalBinMay05, breaks = c(-1000000, -1, 0, 3000, 10000, 25000, 50000, 100000, 250000, 500000, 1000000),
                 labels = c("NegMayBal", "ZeroMayBal", "3KMayBal", "10KMayBal", "25KMayBal", "50KMayBal", "100KMayBal", "250KMayBal", "500KMayBal", "1milMayBal"))
dcc$BalBinMay05 <- BalMayCut

dcc$BalBinApr05 <- paste(dcc$BalApr05)
dcc$BalBinApr05 <- as.numeric(as.character(dcc$BalBinApr05))
sapply(dcc$BalBinApr05, class)
BalAprCut <- cut(dcc$BalBinApr05, breaks = c(-1000000, -1, 0, 3000, 10000, 25000, 50000, 100000, 250000, 500000, 1000000),
                 labels = c("NegAprBal", "ZeroAprBal", "3KAprBal", "10KAprBal", "25KAprBal", "50KAprBal", "100KAprBal", "250KAprBal", "500KAprBal", "1milAprBal"))
dcc$BalBinApr05 <- BalAprCut

dcc$PayAmtBinSep05 <- paste(dcc$PayAmtSep05)
dcc$PayAmtBinSep05 <- as.numeric(as.character(dcc$PayAmtBinSep05))
sapply(dcc$PayAmtBinSep05, class)
PaySepCut <- cut(dcc$PayAmtBinSep05, breaks = c(-1000000, 0, 1000, 1500, 2000, 2500, 5000, 10000, 25000, 100000, 1000000),
                 labels = c("ZeroPayAmtSep", "1KPayAmtSep", "1.5KPayAmtSep", "2KPayAmtSep", "2.5KPayAmtSep", "5KPayAmtSep", "10KPayAmtSep", "25KPayAmtSep", "100KPayAmtSep", ">100KPayAmtSep"))
dcc$PayAmtBinSep05 <- PaySepCut

dcc$PayAmtBinAug05 <- paste(dcc$PayAmtAug05)
dcc$PayAmtBinAug05 <- as.numeric(as.character(dcc$PayAmtBinAug05))
sapply(dcc$PayAmtBinAug05, class)
PayAugCut <- cut(dcc$PayAmtBinAug05, breaks = c(-1000000, 0, 1000, 1500, 2000, 2500, 5000, 10000, 25000, 100000, 1000000),
                 labels = c("ZeroPayAmtAug", "1KPayAmtAug", "1.5KPayAmtAug", "2KPayAmtAug", "2.5KPayAmtAug", "5KPayAmtAug", "10KPayAmtAug", "25KPayAmtAug", "100KPayAmtAug", ">100KPayAmtAug"))
dcc$PayAmtBinAug05 <- PayAugCut

dcc$PayAmtBinJul05 <- paste(dcc$PayAmtJul05)
dcc$PayAmtBinJul05 <- as.numeric(as.character(dcc$PayAmtBinJul05))
sapply(dcc$PayAmtBinJul05, class)
PayJulCut <- cut(dcc$PayAmtBinJul05, breaks = c(-1000000, 0, 1000, 1500, 2000, 2500, 5000, 10000, 25000, 100000, 1000000),
                 labels = c("ZeroPayAmtJul", "1KPayAmtJul", "1.5KPayAmtJul", "2KPayAmtJul", "2.5KPayAmtJul", "5KPayAmtJul", "10KPayAmtJul", "25KPayAmtJul", "100KPayAmtJul", ">100KPayAmtJul"))
dcc$PayAmtBinJul05 <- PayJulCut

dcc$PayAmtBinJun05 <- paste(dcc$PayAmtJun05)
dcc$PayAmtBinJun05 <- as.numeric(as.character(dcc$PayAmtBinJun05))
sapply(dcc$PayAmtBinJun05, class)
PayJunCut <- cut(dcc$PayAmtBinJun05, breaks = c(-1000000, 0, 1000, 1500, 2000, 2500, 5000, 10000, 25000, 100000, 1000000),
                 labels = c("ZeroPayAmtJun", "1KPayAmtJun", "1.5KPayAmtJun", "2KPayAmtJun", "2.5KPayAmtJun", "5KPayAmtJun", "10KPayAmtJun", "25KPayAmtJun", "100KPayAmtJun", ">100KPayAmtJun"))
dcc$PayAmtBinJun05 <- PayJunCut

dcc$PayAmtBinMay05 <- paste(dcc$PayAmtMay05)
dcc$PayAmtBinMay05 <- as.numeric(as.character(dcc$PayAmtBinMay05))
sapply(dcc$PayAmtBinMay05, class)
PayMayCut <- cut(dcc$PayAmtBinMay05, breaks = c(-1000000, 0, 1000, 1500, 2000, 2500, 5000, 10000, 25000, 100000, 1000000),
                 labels = c("ZeroPayAmtMay", "1KPayAmtMay", "1.5KPayAmtMay", "2KPayAmtMay", "2.5KPayAmtMay", "5KPayAmtMay", "10KPayAmtMay", "25KPayAmtMay", "100KPayAmtMay", ">100KPayAmtMay"))
dcc$PayAmtBinMay05 <- PayMayCut

dcc$PayAmtBinApr05 <- paste(dcc$PayAmtApr05)
dcc$PayAmtBinApr05 <- as.numeric(as.character(dcc$PayAmtBinApr05))
sapply(dcc$PayAmtBinApr05, class)
PayAprCut <- cut(dcc$PayAmtBinApr05, breaks = c(-1000000, 0, 1000, 1500, 2000, 2500, 5000, 10000, 25000, 100000, 1000000),
                 labels = c("ZeroPayAmtApr", "1KPayAmtApr", "1.5KPayAmtApr", "2KPayAmtApr", "2.5KPayAmtApr", "5KPayAmtApr", "10KPayAmtApr", "25KPayAmtApr", "100KPayAmtApr", ">100KPayAmtApr"))
dcc$PayAmtBinApr05 <- PayAprCut
```

## Preliminary Exploration

``` {r eval = FALSE}
# Examine baseline default rate
table(dcc$DefaultOct05)/length(dcc$DefaultOct05)
```

##### Credit Limit

``` {r eval = FALSE}
# Plot examining default rate based on credit limit
hlines <- data.frame(baseline = 0.2212, label = "Baseline default rate")
ggplot(dcc, aes(LimitAmtBin, fill=Default1Oct05)) + 
  geom_bar(position = position_fill(), colour = "black") +
  theme(axis.text.x = element_text(angle = 60, hjust=1), plot.title = element_text(hjust = 0.5)) + 
  labs(title = "Credit Limit Amount vs Default", x = "Limit Amount Bin", y = "Percentage") +
  guides(fill=guide_legend(title = "October Action")) +
  scale_y_continuous(labels = scales::percent) +
  geom_hline(data = hlines, aes(yintercept = baseline, colour = label)) + 
  scale_colour_manual(NULL, values = "green")
```

##### Age

``` {r eval = FALSE}
# Plot examining default rate based on age
hlines <- data.frame(baseline = 0.2212, label = "Baseline default rate")
ggplot(dcc, aes(AgeBin, fill=Default1Oct05)) + 
  geom_bar(position = position_fill(), colour = "black") +
  theme(axis.text.x = element_text(angle = 60, hjust=1), plot.title = element_text(hjust = 0.5)) + 
  labs(title = "Age vs Default", x = "Age Bin", y = "Percentage") +
  guides(fill=guide_legend(title = "October Action")) +
  scale_y_continuous(labels = scales::percent) +
  geom_hline(data = hlines, aes(yintercept = baseline, colour = label)) + 
  scale_colour_manual(NULL, values = "green")
```

##### Education

``` {r eval = FALSE}
# Plot examining default rate based on education
hlines <- data.frame(baseline = 0.2212, label = "Baseline default rate")
ggplot(dcc, aes(Education1, fill=Default1Oct05)) + 
  geom_bar(position = position_fill(), colour = "black") +
  theme(axis.text.x = element_text(angle = 60, hjust=1), plot.title = element_text(hjust = 0.5)) + 
  labs(title = "Education vs Default", x = "Education Level", y = "Percentage") +
  guides(fill=guide_legend(title = "October Action")) +
  scale_y_continuous(labels = scales::percent) +
  geom_hline(data = hlines, aes(yintercept = baseline, colour = label)) + 
  scale_colour_manual(NULL, values = "green")
```

##### Gender

``` {r eval = FALSE}
# Plot examining default rate based on gender
hlines <- data.frame(baseline = 0.2212, label = "Baseline default rate")
ggplot(dcc, aes(Gender1, fill=Default1Oct05)) + 
  geom_bar(position = position_fill(), colour = "black") +
  theme(axis.text.x = element_text(angle = 60, hjust=1), plot.title = element_text(hjust = 0.5)) + 
  labs(title = "Gender vs Default", x = "Gender", y = "Percentage") +
  guides(fill=guide_legend(title = "October Action")) +
  scale_y_continuous(labels = scales::percent) +
  geom_hline(data = hlines, aes(yintercept = baseline, colour = label)) + 
  scale_colour_manual(NULL, values = "green")
```

##### Marriage

``` {r eval = FALSE}
# Plot examining default rate based on marriage
hlines <- data.frame(baseline = 0.2212, label = "Baseline default rate")
ggplot(dcc, aes(Marriage1, fill=Default1Oct05)) + 
  geom_bar(position = position_fill(), colour = "black") +
  theme(axis.text.x = element_text(angle = 60, hjust=1), plot.title = element_text(hjust = 0.5)) + 
  labs(title = "Marriage vs Default", x = "Marriage Status", y = "Percentage") +
  guides(fill=guide_legend(title = "October Action")) +
  scale_y_continuous(labels = scales::percent) +
  geom_hline(data = hlines, aes(yintercept = baseline, colour = label)) + 
  scale_colour_manual(NULL, values = "green")
```

##### Monthly Payment Status

``` {r eval = FALSE}
# Plot examining default rate based on monthly payment status
hlines <- data.frame(baseline = 0.2212, label = "Baseline default rate")
ggplot(dcc, aes(Status1Sep05, fill=Default1Oct05)) + 
  geom_bar(position = position_fill(), colour = "black") +
  theme(axis.text.x = element_text(angle = 60, hjust=1), plot.title = element_text(hjust = 0.5)) + 
  labs(title = "September Payment Status vs Default", x = "Payment Status", y = "Percentage") +
  guides(fill=guide_legend(title = "October Action")) +
  scale_y_continuous(labels = scales::percent) +
  geom_hline(data = hlines, aes(yintercept = baseline, colour = label)) + 
  scale_colour_manual(NULL, values = "green")
```

##### Monthly Payment Amount

``` {r eval = FALSE}
# Plot examining default rate based on monthly payment amount
hlines <- data.frame(baseline = 0.2212, label = "Baseline default rate")
ggplot(dcc, aes(PayAmtBinSep05, fill=Default1Oct05)) + 
  geom_bar(position = position_fill(), colour = "black") +
  theme(axis.text.x = element_text(angle = 60, hjust=1), plot.title = element_text(hjust = 0.5)) + 
  labs(title = "September Pay Amount vs Default", x = "Payment Amount", y = "Percentage") +
  guides(fill=guide_legend(title = "October Action")) +
  scale_y_continuous(labels = scales::percent) +
  geom_hline(data = hlines, aes(yintercept = baseline, colour = label)) + 
  scale_colour_manual(NULL, values = "green")
```

## Machine Learning

### Logistic Regression

``` {r eval = FALSE}
# Split data into training and testing set with a 75/25 ratio
set.seed(64)
split = sample.split(dcc$DefaultOct05, SplitRatio = 0.75)
dccTrain = subset(dcc, split == TRUE)
dccTest = subset(dcc, split == FALSE)
```

``` {r eval = FALSE}
# Check rows for both the training and testing set
nrow(dccTrain)
nrow(dccTest)
```

##### Model1

``` {r eval = FALSE}
# Model 1 starts with almost all the independent variables
dccLog1 = glm(DefaultOct05 ~ LimitAmt + Gender + Education + Marriage + Age +
                StatusSep05 + StatusAug05 + StatusJul05 + StatusJun05 + StatusMay05 +
                StatusApr05 + PayAmtSep05 + PayAmtAug05 + PayAmtMay05 + PayAmtApr05 +
                BalSep05 + BalAug05 + BalJul05 + BalJun05 + BalMay05 + BalApr05, 
              data=dccTrain, family=binomial)

summary(dccLog1)
```

##### Model2

``` {r eval = FALSE}
# Model 2 removes insignificant variables
dccLog2 = glm(DefaultOct05 ~ LimitAmt + Gender + Marriage + Age +
                StatusSep05 + StatusAug05 + StatusJul05 + PayAmtSep05 + PayAmtAug05 + 
                PayAmtMay05 + BalSep05 + BalAug05 + BalMay05 + BalApr05, 
              data=dccTrain, family=binomial)

summary(dccLog2)
```

##### Model3

``` {r eval = FALSE}
# Model 3 removes one more that is insignificant
dccLog3 = glm(DefaultOct05 ~ LimitAmt + Gender + Marriage + Age +
                StatusSep05 + StatusAug05 + StatusJul05 + PayAmtSep05 + PayAmtAug05 + 
                PayAmtMay05 + BalSep05 + BalAug05 + BalApr05, 
              data=dccTrain, family=binomial)

summary(dccLog3)
```

##### Model4

``` {r eval = FALSE}
# Model 4 shows all remaining variables with significance
dccLog4 = glm(DefaultOct05 ~ LimitAmt + Gender + Marriage + Age +
                StatusSep05 + StatusAug05 + StatusJul05 + PayAmtSep05 + PayAmtAug05 + 
                PayAmtMay05 + BalSep05 + BalAug05, 
              data=dccTrain, family=binomial)

summary(dccLog4)
```

#### Predict the data

``` {r eval = FALSE}
# Prediction on Test data with 0.5 threshold
predictdccTest = predict(dccLog4, type="response", newdata = dccTest)
table(dccTest$DefaultOct05, predictdccTest > 0.5)
```

``` {r eval = FALSE}
# Check for accuracy of model
TestAccuracy = (5682 + 408)/(5682 + 408 + 1251 + 159)
TestAccuracy
```

### Classification Tree

``` {r eval = FALSE}
# Split data and create train/test sets
set.seed(64)
split = sample.split(dcc$DefaultOct05, SplitRatio = 0.75)
dccTrain = subset(dcc, split == TRUE)
dccTest = subset(dcc, split == FALSE)
```

``` {r eval = FALSE}
# Build classification tree model with all variables
dccTree = rpart(DefaultOct05 ~ LimitAmtBin + Gender1 + Education1 + Marriage1 + AgeBin + StatusSep05 + 
                  StatusAug05 + StatusJul05 + StatusJun05 + StatusMay05 + StatusApr05 +
                  PayAmtSep05 + PayAmtAug05 + PayAmtJul05 + PayAmtJun05 + PayAmtMay05 + 
                  PayAmtApr05 + BalSep05 + BalAug05 + BalJul05 + BalJun05 + BalMay05 + BalApr05, 
                data = dccTrain, method = "class", control = rpart.control(minbucket = 25))

# Look at tree
prp(dccTree)
```

``` {r eval = FALSE}
# Build classification tree model2 with all variables and cp = .0025
dccTree2 = rpart(DefaultOct05 ~ LimitAmtBin + Gender1 + Education1 + Marriage1 + AgeBin + 
                  StatusSep05 + StatusAug05 + StatusJul05 + StatusJun05 + StatusMay05 +
                  StatusApr05 + PayAmtSep05 + PayAmtAug05 + PayAmtJul05 + PayAmtJun05 + 
                  PayAmtMay05 + PayAmtApr05 + BalSep05 + BalAug05 + BalJul05 + 
                  BalJun05 + BalMay05 + BalApr05, 
                data = dccTrain, method = "class", 
                control = rpart.control(minbucket = 25, cp = .0025))

# Look at tree
prp(dccTree2)
```

``` {r eval = FALSE}
# Build classification tree model3 with all variables and cp = .001
dccTree3 = rpart(DefaultOct05 ~ LimitAmtBin + Gender1 + Education1 + Marriage1 + AgeBin + 
                  StatusSep05 + StatusAug05 + StatusJul05 + StatusJun05 + StatusMay05 +
                  StatusApr05 + PayAmtSep05 + PayAmtAug05 + PayAmtJul05 + PayAmtJun05 + 
                  PayAmtMay05 + PayAmtApr05 + BalSep05 + BalAug05 + BalJul05 + 
                  BalJun05 + BalMay05 + BalApr05, 
                data = dccTrain, method = "class", 
                control = rpart.control(minbucket = 25, cp = .001))

# Look at tree
prp(dccTree3)
```

``` {r eval = FALSE}
# Apply three models on test set
PredictCARTdcc = predict(dccTree, newdata = dccTest, type = "class")
table(dccTest$DefaultOct05, PredictCARTdcc)

PredictCART2dcc = predict(dccTree2, newdata = dccTest, type = "class")
table(dccTest$DefaultOct05, PredictCART2dcc)

PredictCART3dcc = predict(dccTree3, newdata = dccTest, type = "class")
table(dccTest$DefaultOct05, PredictCART3dcc)
```

``` {r eval = FALSE}
# Examine accuracy of each model
CAccuracy = (5615 + 546)/(5615 + 546 + 1113 + 226)
CAccuracy

CA2ccuracy = (5594 + 562)/(5594 + 562 + 1097 + 247)
CA2ccuracy

CA3ccuracy = (5532 + 615)/(5532 + 615 + 1046 + 309)
CA3ccuracy
```

### Random Forest

``` {r eval = FALSE}
# Split data, build model, apply to test set
set.seed(64)
split = sample.split(dcc$DefaultOct05, SplitRatio = 0.75)
dccTrain = subset(dcc, split == TRUE)
dccTest = subset(dcc, split == FALSE)

dccTrain$Default1Oct05 = as.factor(dccTrain$Default1Oct05)
dccTest$Default1Oct05 = as.factor(dccTest$Default1Oct05)

dccForest = randomForest(Default1Oct05 ~ LimitAmtBin + Gender + Education + AgeBin + StatusSep05 + 
                           StatusAug05 + StatusJul05 + StatusJun05 + StatusMay05 + StatusApr05 +
                           PayAmtSep05 + PayAmtAug05 + PayAmtJul05 + PayAmtJun05 + PayAmtMay05 +
                           PayAmtApr05 +BalSep05 + BalAug05 + BalJul05 + BalJun05 + BalMay05 + 
                           BalApr05, data = dccTrain, nodesize = 25, ntree = 200)

PredictdccForest = predict(dccForest, newdata = dccTest)
table(dccTest$DefaultOct05, PredictdccForest)
```

``` {r eval = FALSE}
# Examine accuracy
RAccuracy = (5548 + 598)/(5548 + 598 + 1061 + 293)
RAccuracy
```